/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shoe({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./models/shoe.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={3}>
      <mesh geometry={nodes.shoe.geometry} material={materials.laces} material-color={props.customColor.lace}/>
      <mesh geometry={nodes.shoe_1.geometry} material={materials.mesh} material-color={props.customColor.mesh}/>
      <mesh geometry={nodes.shoe_2.geometry} material={materials.caps} material-color={""}/>
      <mesh geometry={nodes.shoe_3.geometry} material={materials.inner} material-color={""}/>
      <mesh geometry={nodes.shoe_4.geometry} material={materials.sole} material-color={""}/>
      <mesh geometry={nodes.shoe_5.geometry} material={materials.stripes} material-color={props.customColor.stripe}/>
      <mesh geometry={nodes.shoe_6.geometry} material={materials.band} material-color={""}/>
      <mesh geometry={nodes.shoe_7.geometry} material={materials.patch} material-color={""}/>
    </group>
  )
}

useGLTF.preload('./models/shoe.gltf')
